version: "3.6"
services:

######### MANAGEMENT ##########

 # portainer - docker management
  portainer:
    image: portainer/portainer
    hostname: portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/conf/portainer/data:/data
      - /opt/conf/portainer/shared/:/shared
    environment:
      - TZ=America/Los_Angeles

 # organizr - muxer WebUI
  organizr:
    image: organizrtools/organizr-v2
    container_name: organizr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /opt/conf/organizr:/config
    ports:
      - 81:80
    restart: unless-stopped

 # pi-hole - DNS service
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    cap_add:
      - NET_ADMIN
    environment:
      ServerIP: 192.168.1.3
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.hixon.io
      VIRTUAL_PORT: 80
    extra_hosts:
      - 'pihole.hixon.io:192.168.1.3'
    volumes:
      - /etc/pihole/:/etc/pihole/
      - /opt/conf/pihole/lighthttpd.conf:/etc/lighthttpd/lighthttpd.conf
      - /etc/resolv.conf:/etc/resolv.conf
      # WARNING: if this log don't exist as a file on the host already
      # docker will try to create a directory in it's place making for lots of errors
      - '/var/log/pihole.log:/var/log/pihole.log'
    restart: always

 # watchtower - automagically update containers
  watchtower:
    container_name: watchtower
    hostname: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup

