version: "3.6"
services:

######### DOWNLOAD CLIENTS ##########

  # sabnzbd - .nzb download daemon
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    env_file: uidgid.env
    volumes:
      - /opt/conf/sabnzbd/incomplete:/incomplete-downloads
      - /opt/conf/sabnzbd/:/config
      - /opt/conf/sabnzbd/downloads:/downloads
    ports:
      - 8080:8080
    environment:
      - EDGE=1
      - VIRTUAL_HOST=sabnzbd.hixon.io
      - VIRTUAL_PORT=8080
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.1.3:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

   # deluge - Torrent daemon
  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    restart: always
    ports:
      - 8112:8112
    volumes:
      - /opt/conf/deluge/config:/config
      - /opt/conf/deluge/downloads:/downloads
      - /opt/conf/jackett/shared:/shared
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Los_Angeles
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.1.3:8112"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
